// src/config/materialRegistry.ts
// Static catalog of ~45 PBR materials for the Form+Skin system.
// Each material maps to one or more skin slot IDs.

import type { MaterialOption } from '@/types/sceneObject';

const ALL_METAL_SLOTS = ['frame', 'handle', 'track', 'plate', 'fixture', 'housing', 'trim', 'sill', 'base'];
const ALL_GLASS_SLOTS = ['glass'];
const ALL_PANEL_SLOTS = ['panel', 'trim', 'sill'];
const ALL_TEXTILE_SLOTS = ['shade', 'cord', 'heads', 'paper'];
const ALL_SYNTH_SLOTS = ['panel', 'trim', 'housing', 'base', 'sill'];
const ALL_WOOD_SLOTS = ['panel', 'sill', 'trim', 'base', 'wall'];

const MATERIALS: MaterialOption[] = [
  // ── Metals (15) ──────────────────────────────────────────────────────────
  {
    id: 'raw_steel',
    label: 'Raw Steel',
    color: '#7a7d82',
    metalness: 0.85,
    roughness: 0.55,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'brushed_aluminum',
    label: 'Brushed Aluminum',
    color: '#b8bcc4',
    metalness: 0.90,
    roughness: 0.40,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'matte_black',
    label: 'Matte Black',
    color: '#1c1c1e',
    metalness: 0.70,
    roughness: 0.80,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'gunmetal',
    label: 'Gunmetal',
    color: '#2c3038',
    metalness: 0.80,
    roughness: 0.50,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'polished_chrome',
    label: 'Polished Chrome',
    color: '#d4d8df',
    metalness: 0.95,
    roughness: 0.05,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'dark_chrome',
    label: 'Dark Chrome',
    color: '#3a3d42',
    metalness: 0.92,
    roughness: 0.08,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'oxidized_copper',
    label: 'Oxidized Copper',
    color: '#4a8c7a',
    metalness: 0.75,
    roughness: 0.70,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'blackened_brass',
    label: 'Blackened Brass',
    color: '#3d3520',
    metalness: 0.82,
    roughness: 0.45,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'wrought_iron',
    label: 'Wrought Iron',
    color: '#252628',
    metalness: 0.78,
    roughness: 0.75,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'anodized_aluminum',
    label: 'Anodized Aluminum',
    color: '#4a5568',
    metalness: 0.85,
    roughness: 0.35,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'carbon_fiber',
    label: 'Carbon Fiber',
    color: '#1a1c20',
    metalness: 0.60,
    roughness: 0.30,
    applicableTo: [...ALL_METAL_SLOTS, ...ALL_PANEL_SLOTS],
  },
  {
    id: 'polished_brass',
    label: 'Polished Brass',
    color: '#c9a84c',
    metalness: 0.90,
    roughness: 0.15,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'titanium_grey',
    label: 'Titanium Grey',
    color: '#6b7280',
    metalness: 0.88,
    roughness: 0.30,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'diamond_plate',
    label: 'Diamond Plate',
    color: '#8a9099',
    metalness: 0.82,
    roughness: 0.60,
    applicableTo: ['plate', 'base', 'floor', 'frame'],
  },
  {
    id: 'cerakote_dark_earth',
    label: 'Cerakote Dark Earth',
    color: '#5c4a2a',
    metalness: 0.65,
    roughness: 0.72,
    applicableTo: ALL_METAL_SLOTS,
  },

  // ── Woods (10) ───────────────────────────────────────────────────────────
  {
    id: 'light_oak',
    label: 'Light Oak',
    color: '#c8a96e',
    metalness: 0.0,
    roughness: 0.80,
    applicableTo: ALL_WOOD_SLOTS,
  },
  {
    id: 'warm_oak',
    label: 'Warm Oak',
    color: '#b07d45',
    metalness: 0.0,
    roughness: 0.78,
    applicableTo: ALL_WOOD_SLOTS,
  },
  {
    id: 'walnut',
    label: 'Walnut',
    color: '#5c3d1e',
    metalness: 0.0,
    roughness: 0.82,
    applicableTo: ALL_WOOD_SLOTS,
  },
  {
    id: 'hinoki_cypress',
    label: 'Hinoki Cypress',
    color: '#e8d5b0',
    metalness: 0.0,
    roughness: 0.75,
    applicableTo: ALL_WOOD_SLOTS,
  },
  {
    id: 'bleached_wood',
    label: 'Bleached Wood',
    color: '#e0d5c4',
    metalness: 0.0,
    roughness: 0.70,
    applicableTo: ALL_WOOD_SLOTS,
  },
  {
    id: 'reclaimed_barn',
    label: 'Reclaimed Barn Wood',
    color: '#7a5c3a',
    metalness: 0.02,
    roughness: 0.92,
    applicableTo: ALL_WOOD_SLOTS,
  },
  {
    id: 'dark_teak',
    label: 'Dark Teak',
    color: '#4a2e1a',
    metalness: 0.0,
    roughness: 0.85,
    applicableTo: ALL_WOOD_SLOTS,
  },
  {
    id: 'laser_cut_plywood',
    label: 'Laser-Cut Plywood',
    color: '#d4b87a',
    metalness: 0.0,
    roughness: 0.78,
    applicableTo: ALL_WOOD_SLOTS,
  },
  {
    id: 'bamboo_composite',
    label: 'Bamboo Composite',
    color: '#c4b56a',
    metalness: 0.0,
    roughness: 0.72,
    applicableTo: ALL_WOOD_SLOTS,
  },
  {
    id: 'mesquite_wood',
    label: 'Mesquite Wood',
    color: '#6e3d1c',
    metalness: 0.0,
    roughness: 0.88,
    applicableTo: ALL_WOOD_SLOTS,
  },

  // ── Glass (8) ────────────────────────────────────────────────────────────
  {
    id: 'clear_glass',
    label: 'Clear Glass',
    color: '#c8dde8',
    metalness: 0.10,
    roughness: 0.05,
    applicableTo: ALL_GLASS_SLOTS,
  },
  {
    id: 'frosted_glass',
    label: 'Frosted Glass',
    color: '#d8e4ec',
    metalness: 0.08,
    roughness: 0.60,
    applicableTo: ALL_GLASS_SLOTS,
  },
  {
    id: 'smoked_glass',
    label: 'Smoked Glass',
    color: '#3a4048',
    metalness: 0.15,
    roughness: 0.08,
    applicableTo: ALL_GLASS_SLOTS,
  },
  {
    id: 'bronze_tint',
    label: 'Bronze Tint Glass',
    color: '#7a5a30',
    metalness: 0.12,
    roughness: 0.06,
    applicableTo: ALL_GLASS_SLOTS,
  },
  {
    id: 'sea_glass',
    label: 'Sea Glass',
    color: '#7ab8a8',
    metalness: 0.05,
    roughness: 0.45,
    applicableTo: ALL_GLASS_SLOTS,
  },
  {
    id: 'neon_edge_acrylic',
    label: 'Neon-Edge Acrylic',
    color: '#00e5ff',
    metalness: 0.20,
    roughness: 0.10,
    applicableTo: [...ALL_GLASS_SLOTS, 'trim'],
  },
  {
    id: 'fluted_glass',
    label: 'Fluted Glass',
    color: '#ccd9e4',
    metalness: 0.08,
    roughness: 0.55,
    applicableTo: ALL_GLASS_SLOTS,
  },
  {
    id: 'frosted_polycarbonate',
    label: 'Frosted Polycarbonate',
    color: '#dce8f0',
    metalness: 0.05,
    roughness: 0.65,
    applicableTo: [...ALL_GLASS_SLOTS, ...ALL_PANEL_SLOTS],
  },

  // ── Mineral (9) ──────────────────────────────────────────────────────────
  {
    id: 'concrete_grey',
    label: 'Concrete Grey',
    color: '#8c8c8c',
    metalness: 0.0,
    roughness: 0.92,
    applicableTo: [...ALL_PANEL_SLOTS, 'wall', 'base'],
  },
  {
    id: 'raw_concrete',
    label: 'Raw Concrete',
    color: '#a0998a',
    metalness: 0.0,
    roughness: 0.95,
    applicableTo: [...ALL_PANEL_SLOTS, 'wall', 'base'],
  },
  {
    id: 'terracotta',
    label: 'Terracotta',
    color: '#c26f44',
    metalness: 0.0,
    roughness: 0.90,
    applicableTo: [...ALL_PANEL_SLOTS, 'wall'],
  },
  {
    id: 'cork',
    label: 'Cork',
    color: '#c4a87a',
    metalness: 0.0,
    roughness: 0.88,
    applicableTo: [...ALL_PANEL_SLOTS, 'wall'],
  },
  {
    id: 'sand_blasted_steel',
    label: 'Sand-Blasted Steel',
    color: '#909498',
    metalness: 0.55,
    roughness: 0.88,
    applicableTo: ALL_METAL_SLOTS,
  },
  {
    id: 'sun_baked_clay',
    label: 'Sun-Baked Clay',
    color: '#b8855a',
    metalness: 0.0,
    roughness: 0.93,
    applicableTo: [...ALL_PANEL_SLOTS, 'wall'],
  },
  {
    id: 'marble_composite',
    label: 'Marble Composite',
    color: '#e8e2d8',
    metalness: 0.05,
    roughness: 0.20,
    applicableTo: [...ALL_PANEL_SLOTS, 'wall', 'base'],
  },
  {
    id: 'terrazzo',
    label: 'Terrazzo',
    color: '#c8c0b0',
    metalness: 0.02,
    roughness: 0.35,
    applicableTo: [...ALL_PANEL_SLOTS, 'wall', 'base'],
  },
  {
    id: 'ceramic_tile',
    label: 'Ceramic Tile',
    color: '#e4dfd4',
    metalness: 0.05,
    roughness: 0.25,
    applicableTo: [...ALL_PANEL_SLOTS, 'wall'],
  },

  // ── Textile (5) ──────────────────────────────────────────────────────────
  {
    id: 'rice_paper_washi',
    label: 'Rice Paper Washi',
    color: '#f0e8d4',
    metalness: 0.0,
    roughness: 0.95,
    applicableTo: ALL_TEXTILE_SLOTS,
  },
  {
    id: 'woven_rattan',
    label: 'Woven Rattan',
    color: '#c8a85c',
    metalness: 0.0,
    roughness: 0.90,
    applicableTo: ALL_TEXTILE_SLOTS,
  },
  {
    id: 'palm_fiber',
    label: 'Palm Fiber',
    color: '#9a7a40',
    metalness: 0.0,
    roughness: 0.92,
    applicableTo: ALL_TEXTILE_SLOTS,
  },
  {
    id: 'leather',
    label: 'Leather',
    color: '#5c3820',
    metalness: 0.0,
    roughness: 0.75,
    applicableTo: [...ALL_TEXTILE_SLOTS, 'panel'],
  },
  {
    id: 'ballistic_nylon',
    label: 'Ballistic Nylon',
    color: '#2a2e32',
    metalness: 0.0,
    roughness: 0.88,
    applicableTo: ALL_TEXTILE_SLOTS,
  },

  // ── Synthetic (15) ───────────────────────────────────────────────────────
  {
    id: 'white_laminate',
    label: 'White Laminate',
    color: '#f4f4f4',
    metalness: 0.02,
    roughness: 0.30,
    applicableTo: ALL_SYNTH_SLOTS,
  },
  {
    id: 'black_lacquer',
    label: 'Black Lacquer',
    color: '#141416',
    metalness: 0.10,
    roughness: 0.08,
    applicableTo: ALL_SYNTH_SLOTS,
  },
  {
    id: 'powder_coat_white',
    label: 'Powder Coat White',
    color: '#f0f0f0',
    metalness: 0.45,
    roughness: 0.65,
    applicableTo: [...ALL_METAL_SLOTS, ...ALL_SYNTH_SLOTS],
  },
  {
    id: 'powder_coat_sage',
    label: 'Powder Coat Sage',
    color: '#7a9c80',
    metalness: 0.45,
    roughness: 0.65,
    applicableTo: [...ALL_METAL_SLOTS, ...ALL_SYNTH_SLOTS],
  },
  {
    id: 'powder_coat_coral',
    label: 'Powder Coat Coral',
    color: '#e06050',
    metalness: 0.45,
    roughness: 0.65,
    applicableTo: [...ALL_METAL_SLOTS, ...ALL_SYNTH_SLOTS],
  },
  {
    id: 'powder_coat_sky',
    label: 'Powder Coat Sky',
    color: '#5ba8d8',
    metalness: 0.45,
    roughness: 0.65,
    applicableTo: [...ALL_METAL_SLOTS, ...ALL_SYNTH_SLOTS],
  },
  {
    id: 'powder_coat_mustard',
    label: 'Powder Coat Mustard',
    color: '#d4a828',
    metalness: 0.45,
    roughness: 0.65,
    applicableTo: [...ALL_METAL_SLOTS, ...ALL_SYNTH_SLOTS],
  },
  {
    id: 'powder_coat_blush',
    label: 'Powder Coat Blush',
    color: '#e8a8a0',
    metalness: 0.45,
    roughness: 0.65,
    applicableTo: [...ALL_METAL_SLOTS, ...ALL_SYNTH_SLOTS],
  },
  {
    id: 'pla_white',
    label: 'PLA White',
    color: '#f8f8f8',
    metalness: 0.0,
    roughness: 0.55,
    applicableTo: ALL_SYNTH_SLOTS,
  },
  {
    id: 'pla_grey',
    label: 'PLA Grey',
    color: '#9090a0',
    metalness: 0.0,
    roughness: 0.58,
    applicableTo: ALL_SYNTH_SLOTS,
  },
  {
    id: 'pla_black',
    label: 'PLA Black',
    color: '#202028',
    metalness: 0.0,
    roughness: 0.55,
    applicableTo: ALL_SYNTH_SLOTS,
  },
  {
    id: 'painted_white',
    label: 'Painted White',
    color: '#f0eeea',
    metalness: 0.0,
    roughness: 0.82,
    applicableTo: [...ALL_SYNTH_SLOTS, 'wall'],
  },
  {
    id: 'painted_sage',
    label: 'Painted Sage',
    color: '#88a888',
    metalness: 0.0,
    roughness: 0.85,
    applicableTo: [...ALL_SYNTH_SLOTS, 'wall'],
  },
  {
    id: 'matte_od_green',
    label: 'Matte OD Green',
    color: '#4a5c38',
    metalness: 0.30,
    roughness: 0.90,
    applicableTo: [...ALL_METAL_SLOTS, ...ALL_SYNTH_SLOTS],
  },
  {
    id: 'pastel_steel',
    label: 'Pastel Steel',
    color: '#b8ccd8',
    metalness: 0.55,
    roughness: 0.60,
    applicableTo: ALL_METAL_SLOTS,
  },
];

export const materialRegistry: Map<string, MaterialOption> = new Map(
  MATERIALS.map((m) => [m.id, m])
);

export function getMaterial(id: string): MaterialOption | undefined {
  return materialRegistry.get(id);
}
